# Generated by Django 3.1.7 on 2023-11-20 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auction_id', models.AutoField(db_column='Auction_ID', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, db_column='Start_Time', null=True)),
                ('minimum_price', models.DecimalField(blank=True, db_column='Minimum_Price', decimal_places=2, max_digits=10, null=True)),
                ('ending_time', models.DateTimeField(blank=True, db_column='Ending_Time', null=True)),
                ('additional_info', models.CharField(blank=True, db_column='Additional_Info', max_length=50, null=True)),
                ('minimum_deposit', models.DecimalField(blank=True, db_column='Minimum_Deposit', decimal_places=2, max_digits=10, null=True)),
                ('auction_hold', models.IntegerField(blank=True, db_column='Auction_Hold', null=True)),
                ('auction_status', models.CharField(blank=True, db_column='Auction_Status', max_length=50, null=True)),
                ('is_verified', models.IntegerField(blank=True, null=True)),
                ('payment_id', models.IntegerField(blank=True, db_column='Payment_ID', null=True)),
                ('edit_time', models.CharField(blank=True, db_column='Edit_time', max_length=50, null=True)),
                ('withdrawn', models.CharField(blank=True, db_column='Withdrawn', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Auction',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('shipping_id', models.AutoField(db_column='Shipping_ID', primary_key=True, serialize=False)),
                ('transport_tracking_number', models.CharField(blank=True, db_column='Transport_Tracking_Number', max_length=50, null=True)),
                ('shipping_method', models.CharField(blank=True, db_column='Shipping_Method', max_length=50, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, db_column='Delivered_Date', null=True)),
                ('temp_hold', models.CharField(blank=True, db_column='Temp_hold', max_length=50, null=True)),
                ('shipping_status', models.CharField(blank=True, db_column='Shipping_Status', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Shipping',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('register_date', models.DateField(blank=True, db_column='Register_Date', null=True)),
                ('last_signin', models.DateField(blank=True, db_column='Last_Signin', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=255, null=True)),
                ('isadmin', models.IntegerField(blank=True, db_column='isAdmin', null=True)),
                ('admin_verify', models.IntegerField(blank=True, db_column='Admin_verify', null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('bidder', models.OneToOneField(db_column='Bidder_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usedCarBidding.user')),
                ('minimum_deposit', models.DecimalField(blank=True, db_column='Minimum_Deposit', decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, db_column='Max_Price', decimal_places=2, max_digits=10, null=True)),
                ('auto_bid', models.IntegerField(blank=True, db_column='Auto_Bid', null=True)),
                ('is_verified', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Bidder',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usedCarBidding.user')),
                ('first_car_release_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Seller',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.CharField(db_column='Car_ID', max_length=50, primary_key=True, serialize=False)),
                ('body_style', models.CharField(blank=True, db_column='Body_Style', max_length=50, null=True)),
                ('exterior_color', models.CharField(blank=True, db_column='Exterior_Color', max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, db_column='Transmission', max_length=50, null=True)),
                ('mileage', models.IntegerField(blank=True, db_column='Mileage', null=True)),
                ('engine', models.CharField(blank=True, db_column='Engine', max_length=50, null=True)),
                ('title_status', models.CharField(blank=True, db_column='Title_Status', max_length=50, null=True)),
                ('make', models.CharField(blank=True, db_column='Make', max_length=50, null=True)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('drivetrain', models.CharField(blank=True, db_column='Drivetrain', max_length=50, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=100, null=True)),
                ('current_status', models.CharField(blank=True, db_column='Current_Status', max_length=50, null=True)),
                ('seller', models.ForeignKey(blank=True, db_column='Seller_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usedCarBidding.user')),
            ],
            options={
                'db_table': 'Car',
            },
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('bidding_id', models.AutoField(db_column='Bidding_ID', primary_key=True, serialize=False)),
                ('bidding_price', models.DecimalField(blank=True, db_column='Bidding_Price', decimal_places=2, max_digits=10, null=True)),
                ('auction', models.ForeignKey(blank=True, db_column='Auction_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usedCarBidding.auction')),
                ('bidder', models.ForeignKey(blank=True, db_column='Bidder_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usedCarBidding.user')),
            ],
            options={
                'db_table': 'Bidding',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='car',
            field=models.ForeignKey(blank=True, db_column='Car_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usedCarBidding.car'),
        ),
        migrations.AddField(
            model_name='auction',
            name='shipping',
            field=models.ForeignKey(blank=True, db_column='Shipping_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usedCarBidding.shipping'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, db_column='Winner_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usedCarBidding.user'),
        ),
    ]
