# Generated by Django 3.1.7 on 2023-11-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usedCarBidding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='car',
            new_name='car_id',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='shipping',
            new_name='shipping_id',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='winner',
            new_name='winner_id',
        ),
        migrations.RenameField(
            model_name='bidder',
            old_name='bidder',
            new_name='bidder_id',
        ),
        migrations.RenameField(
            model_name='bidding',
            old_name='auction',
            new_name='auction_id',
        ),
        migrations.RenameField(
            model_name='bidding',
            old_name='bidder',
            new_name='bidder_id',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='seller',
            new_name='seller_id',
        ),
        migrations.AlterField(
            model_name='auction',
            name='is_verified',
            field=models.IntegerField(blank=True, db_column='is_verified', null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='first_car_release_date',
            field=models.DateField(blank=True, db_column='first_car_release_date', null=True),
        ),
    ]
