# Generated by Django 3.1.7 on 2023-12-01 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usedCarBidding', '0002_auto_20231201_0357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='car',
            new_name='car_id',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='car',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='bidding_price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='shipped_date',
        ),
        migrations.AddField(
            model_name='auction',
            name='additional_info',
            field=models.CharField(blank=True, db_column='Additional_Info', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_hold',
            field=models.IntegerField(blank=True, db_column='Auction_Hold', null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_status',
            field=models.CharField(blank=True, db_column='Auction_Status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='car_id',
            field=models.ForeignKey(blank=True, db_column='Car_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usedCarBidding.car'),
        ),
        migrations.AddField(
            model_name='auction',
            name='edit_time',
            field=models.CharField(blank=True, db_column='Edit_time', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='is_verified',
            field=models.IntegerField(blank=True, db_column='is_verified', null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='minimum_deposit',
            field=models.DecimalField(blank=True, db_column='Minimum_Deposit', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='payment_id',
            field=models.IntegerField(blank=True, db_column='Payment_ID', null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='shipping_id',
            field=models.ForeignKey(blank=True, db_column='Shipping_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usedCarBidding.shipping'),
        ),
        migrations.AddField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(blank=True, db_column='Start_Time', null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner_id',
            field=models.ForeignKey(blank=True, db_column='Winner_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction',
            name='withdrawn',
            field=models.CharField(blank=True, db_column='Withdrawn', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bidding',
            name='auction_id',
            field=models.ForeignKey(blank=True, db_column='Auction_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usedCarBidding.auction'),
        ),
        migrations.AddField(
            model_name='car',
            name='drivetrain',
            field=models.CharField(blank=True, db_column='Drivetrain', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, db_column='Engine', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='exterior_color',
            field=models.CharField(blank=True, db_column='Exterior_Color', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, db_column='Make', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(blank=True, db_column='Mileage', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='seller_id',
            field=models.ForeignKey(blank=True, db_column='Seller_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='title_status',
            field=models.CharField(blank=True, db_column='Title_Status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, db_column='Transmission', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='delivered_date',
            field=models.DateTimeField(blank=True, db_column='Delivered_Date', null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_status',
            field=models.CharField(blank=True, db_column='Shipping_Status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='temp_hold',
            field=models.CharField(blank=True, db_column='Temp_hold', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='ending_time',
            field=models.DateTimeField(blank=True, db_column='Ending_Time', null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='minimum_price',
            field=models.DecimalField(blank=True, db_column='Minimum_Price', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='current_status',
            field=models.CharField(blank=True, db_column='Current_Status', max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='bidding',
            table=None,
        ),
    ]
