# Generated by Django 3.1.7 on 2023-12-02 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usedCarBidding', '0004_auto_20231202_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('CommentID', models.AutoField(db_column='CommentID', primary_key=True, serialize=False)),
                ('CommenContent', models.CharField(db_column='CommenContent', max_length=100)),
                ('create_at', models.DateField(db_column='create_at')),
                ('create_by_user_ID', models.IntegerField(db_column='create_by_user_ID')),
                ('create_by_user_Name', models.CharField(db_column='create_by_user_Name', max_length=100)),
                ('auction_id', models.ForeignKey(db_column='auction_id', on_delete=django.db.models.deletion.CASCADE, to='usedCarBidding.auction')),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('Reply_ID', models.AutoField(db_column='Reply_ID', primary_key=True, serialize=False)),
                ('ReplyContent', models.CharField(db_column='ReplyContent', max_length=100)),
                ('create_at', models.DateField(db_column='create_at')),
                ('create_by_user_ID', models.IntegerField(db_column='create_by_user_ID')),
                ('create_by_user_Name', models.CharField(db_column='create_by_user_Name', max_length=100)),
                ('CommentID', models.ForeignKey(db_column='CommentID', on_delete=django.db.models.deletion.CASCADE, to='usedCarBidding.comments')),
            ],
            options={
                'db_table': 'reply',
            },
        ),
    ]
